language: python

python:
  - "2.7"

before_install:
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libclang-6.0.so.1 /usr/lib/x86_64-linux-gnu/libclang.so

install:
  - (cd cldoc-static && npm install)
  - pip install .
  
addons:
  apt:
    sources:
    - llvm-toolchain-trusty
    packages:
    - libclang-6.0

script:
  - make tests
  
notifications:
  email: false
